apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bulksms-backend
  name: bulksms-backend
spec:
  progressDeadlineSeconds: 300
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: bulksms-backend
  template:
    metadata:
      labels:
        app: bulksms-backend
    spec:
      containers:
        - env:
            - name: DATASOURCE_URL
              value: jdbc:oracle:thin:@//10.160.151.10:1521/BIPRODDB
            - name: DATASOURCE_USERNAME
              value: sercom
            - name: DATASOURCE_PASSWORD
              value: sercom
            - name: SENDSMS_URL
              value: http://10.161.1.238:8080/sms/rest/submit/send-sms
            - name: SENDSMS_URL1
              value: http://10.161.10.169:64805/sms/rest/submit/send-sms
          image: acrsercomcloud.azurecr.io/bulksms-prod:595
          imagePullPolicy: IfNotPresent
          name: bulksms-backend
          ports:
            - containerPort: 7882
              protocol: TCP
          resources:
            limits:
              cpu: '2'
              memory: 4Gi
            requests:
              cpu: 512m
              memory: 4Gi
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
#---
#apiVersion: v1
#kind: Service
#metadata:
#  labels:
#    app: bulksms-backend
#  name: bulksms-backend
#spec:
#  ports:
#    - name: default
#      port: 7882
#      targetPort: 7882
#  selector:
#    app: bulksms-backend
