apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: bulksms-backend
  name: bulksms-backend
spec:
  progressDeadlineSeconds: 300
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: bulksms-backend
  template:
    metadata:
      labels:
        app: bulksms-backend
    spec:
      containers:
        - env:
            - name: DATASOURCE_URL
              value: jdbc:oracle:thin:@//10.160.151.10:1521/BIPRODDB
          image: acrsercomcloud.azurecr.io/bulksms-prod:596
          imagePullPolicy: IfNotPresent
          name: bulksms-backend
          ports:
            - containerPort: 7882
              protocol: TCP
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
#---
#apiVersion: v1
#kind: Service
#metadata:
#  labels:
#    app: bulksms-backend
#  name: bulksms-backend
#spec:
#  ports:
#    - name: default
#      port: 7882
#      targetPort: 7882
#  selector:
#    app: bulksms-backend
